name: CI
on: [push, pull_request]
env:
  UI_VERSION: ${{ github.sha }}
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    steps:
      - uses: actions/checkout@v2

      # Install Node 16
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - run: npm install -g npm@8.5.5

      # Install & build & test:
      - run: npm ci

      - run: npm run test:unit

      # Build & run normal integration tests:
      - name: Build & test
        run: npm run test:integration
        if: github.ref != 'refs/heads/main'

      # Build with secrets & run integrations tests, on main only:
      - name: Build & test for production release
        run: npm run test:integration
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GA_ID: ${{ secrets.GA_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: http-toolkit
          SENTRY_PROJECT: httptoolkit-ui
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  publish-netlify:
    name: Deploy ${{ (github.ref == 'refs/heads/main' && 'to Netlify production') || 'Netlify preview' }}
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './dist'
          production-branch: main # Main goes to prod, others do deploy previews
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: GHA Deploy - ${{ github.event.head_commit.message }}
          enable-commit-status: true
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-config-path: ./netlify.toml
          alias: ${{ github.sha }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  publish-hidora:
    name: Deploy to Docker Hub & Hidora
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: httptoolkit/ui
          tags: |
            type=raw,value=prod,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Deploy to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Redeploy site
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sleep 30 # Wait for Docker Hub to fully publish

          # Trigger a container redeploy:
          curl "https://app.hidora.com/1.0/environment/control/rest/redeploycontainersbygroup?session=$HIDORA_API_TOKEN&envName=htk-ui&nodeGroup=cp&tag=prod&useExistingVolumes=true" | \
             tee /dev/stderr | \
             grep -q 'Node has been successfully updated'

          # Clear CDN cache to re-request content:
          curl -f --request POST \
            --url https://api.bunny.net/pullzone/1110200/purgeCache \
            --header "AccessKey: $BUNNY_SITE_API_KEY"
        env:
          HIDORA_API_TOKEN: ${{ secrets.HIDORA_API_TOKEN }}
          BUNNY_SITE_API_KEY: ${{ secrets.BUNNY_SITE_API_KEY }}